### PR TITLE
feat: support theme colors

### PR DESCRIPTION
**Pull request by ModyQyW**
This PR supports theme colors. Should be a good start?  :-)

### CODE REVIEW

**Comment by Dunqing** [comment]
Thank you for your efforts!!!

It looks like only a few colors are supported here? My first thought was to support all [antd5 tokens](https://ant.design/docs/react/customize-theme) so we could make antd & unocss work together.

**Comment by ModyQyW** [comment]
> It looks like only a few colors are supported here?

Yes. This PR only supports theme colors. I think it is a good start. We can add more tokens steps by steps.

> My first thought was to support all [antd5 tokens](https://ant.design/docs/react/customize-theme) so we could make antd & unocss work together.

I think there are many things under consideration.

For example, antd5 uses `6px` as default border-radius value. We recommend to follow antd5 tokens, which means we should have `.rounded { border-radius: 6px; }`.

However, this will also break uno preset settings, which has `.rounded { border-radius: 0.25rem; }`.

I am not sure if everyone likes these breaks. Maybe we need to add an option like `override?: boolean` or add a prefix? 

Please give me some advice so I can move on and add more tokens later (maybe after my company business). Thanks!

**Comment by Dunqing** [comment]
> For example, antd5 uses `6px` as default border-radius value. We recommend to follow antd5 tokens, which means we should have `.rounded { border-radius: 6px; }`.
> 
> However, this will also break uno preset settings, which has `.rounded { border-radius: 0.25rem; }`.
> 
> I am not sure if everyone likes these breaks. Maybe we need to add an option like `override?: boolean` or add a prefix?
> 
> Please give me some advice so I can move on and add more tokens later (maybe after my company business). Thanks!

Just like the preset name, this preset is tailor-made for antd, so i think we just need to follow the rules of antd.

**Comment by Dunqing** [comment]
You can implement it as you see fit, I haven't worked with `antd` for too long 😩.

**Comment by ModyQyW** [comment]
Will try my best to improve this one and build unocss-preset-element-plus. Thanks for your unocss-preset-theme!

I will handle this pr next week.

**Pull request merged**
